version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    networks:
      - test-net

  jmeter:
    image: justb4/jmeter:5.5
    volumes:
      - .:/jmeter
    depends_on:
      - backend
    networks:
      - test-net
    command: >
      -n -t /jmeter/jmeter.jmx
      -l /jmeter/results.jtl
      -JAPI_HOST=backend

networks:
  test-net:
