name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup Node + Angular
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install frontend dependencies
        run: |
          npm ci

      - name: Install Angular CLI
        run: |
          npm install @angular/cli --save-dev

      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

  unit-and-integration-tests:
    name: Unit & Integration Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: Run frontend unit tests (Angular)
        run: |
          npx ng test -- --watch=false --browsers=ChromeHeadless

      - name: Run backend unit and integration tests (Jest)
        run: |
          cd backend
          npm test

  e2e-tests:
    name: Cypress End-to-End Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install frontend dependencies
        run: npm ci

      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      - name: Start backend server
        run: |
          cd backend
          npm start &
        env:
          MONGO_URL: mongodb://localhost:27017/test

      - name: Start frontend server
        run: |
          npm start &
        env:
          NODE_ENV: test

      - name: Wait for servers to be ready
        run: sleep 10

      - name: Run Cypress tests
        run: npx cypress run


  performance-tests:
    name: JMeter Performance Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: Install JMeter
        run: sudo apt-get install -y jmeter

      - name: Run JMeter test
        run: |
          jmeter -n -t tests/performance/jmeter.jmx -l results.jtl

  security-tests:
    name: OWASP ZAP Scan
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:3000'
