name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Start backend server
        run: |
          npm install --prefix backend
          nohup node backend/server.js &
        env:
          MONGO_URI: mongodb://localhost:27017/angular

      - name: Wait for backend to start
        run: sleep 10

      - name: Check if backend is running
        run: |
          for i in {1..10}; do
            nc -zv localhost 3000 && echo "Backend is up" && exit 0
            echo "Waiting for backend..."
            sleep 5
          done
          echo "Backend did not start in time" && exit 1

      - name: Run tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Run JMeter tests using Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/jmeter \
            justb4/jmeter:5.5 \
            -n -t /jmeter/jmeter.jmx -l /jmeter/results.jtl

      - name: Display JMeter results
        run: cat results.jtl



