name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # adapte si nécessaire

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Install and run JMeter tests
        run: |
          curl -L https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.5.zip -o jmeter.zip
          unzip jmeter.zip -d $HOME
          export JMETER_HOME=$HOME/apache-jmeter-5.5
          export PATH=$JMETER_HOME/bin:$PATH
          jmeter -n -t jmeter.jmx -l results.jtl
          cat results.jtl


