name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # adapte si nécessaire

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Run JMeter tests using Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/jmeter \
            justb4/jmeter:5.5 \
            -n -t /jmeter/jmeter.jmx -l /jmeter/results.jtl

      - name: Display JMeter results
        run: cat results.jtl



