name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        
      - name: Install wait-on
        run: npm install -g wait-on

      - name: Set permissions for mounted directory
        run: sudo chmod -R 777 ${{ github.workspace }}

      - name: Start backend server
        run: |
          npm install --prefix backend
          nohup node backend/server.js --host 0.0.0.0 &
        env:
          MONGO_URI: mongodb://localhost:27017/angular

      - name: Start frontend server
        run: |
          nohup npm start -- --host 0.0.0.0 &
        env:
          PORT: 4200

      - name: Run JMeter tests using Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/jmeter \
            justb4/jmeter:5.5 \
            -n -t /jmeter/jmeter.jmx -l /jmeter/results.jtl

      - name: Display first 50 JMeter results
        run: head -n 51 results.jtl

      # - name: Run Cypress tests
      #   run: npx cypress run

      - name: Run OWASP ZAP
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/zap.yaml:/zap/wrk/zap.yaml \
            -v ${{ github.workspace }}:/zap/wrk/ \
            ghcr.io/zaproxy/zaproxy:latest zap-full-scan.py \
              -c /zap/wrk/zap.yaml

      - name: Run Unit & integration tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless



