name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Start backend server
        run: |
          npm install --prefix backend
          nohup node backend/server.js --host 0.0.0.0 &
        env:
          MONGO_URI: mongodb://localhost:27017/angular

      - name: Start frontend server
        run: |
          nohup npm start -- --host 0.0.0.0 &
        env:
          PORT: 4200

      - name: Wait for frontend to be ready
        run: npx wait-on http://localhost:4200

      - name: Run JMeter tests using Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/jmeter \
            justb4/jmeter:5.5 \
            -n -t /jmeter/jmeter.jmx -l /jmeter/results.jtl

      - name: Display first 50 JMeter results
        run: head -n 51 results.jtl

      - name: Run Cypress tests
        run: npx cypress run
        env: 
          CYPRESS_BASE_URL: http://172.17.0.1:4200

      - name: Run Unit & integration tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless



