name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Start backend server
        run: |
          npm install --prefix backend
          nohup node backend/server.js &
        env:
          MONGO_URI: mongodb://localhost:27017/angular

      - name: Download JMeter
        run: |
          curl -L https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.5.tgz -o jmeter.tgz
          tar -xzf jmeter.tgz
          mv apache-jmeter-5.5 jmeter

      - name: Run tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Run Jmeter tests
        run: jmeter -n -t jmeter.jmx -l results.jtl


